# Site settings
title: BrowserSync
description: "BrowserSync makes your browser testing workflow faster by synchronising URLs, interactions and code changes across multiple devices. It&rsquo;s wicked-fast and totally free."
baseurl: "http://browsersync.io"
highlighter: pygments
url: "http://browsersync.io"
twitter_username: browsersync
github_username: shakshane

# Files config
exclude: ["node_modules", "gulpfile.js", "package.json", "bower.json", "bower_components"]

# Build settings
markdown: kramdown
permalink: pretty

# Assets
cssFile: "css/core.min.css"

env: "production"

navigation:
 - page-label: home
   label: "Get Started"
   url: /index.html#install
 - page-label: docs
   label: "Documentation"
   url: https://github.com/shakyShane/browser-sync/wiki
 - page-label: source
   label: "Source Code"
   url: https://github.com/shakyShane/browser-sync

links:
  docs: "https://github.com/shakyShane/browser-sync/wiki"
  source: "https://github.com/shakyShane/browser-sync"
  twitter: "https://twitter.com/browsersync"